function [psi, nElNds, dim] = elementCall2(elemType, absc)

switch(elemType)
    
    case 1
        % 2 node
        %        1------2
        dim = size(absc,1);
        csi = absc(1,:)';
        
        psi.sf=[...
            1/2*(1-csi),...
            1/2*(1+csi)];
        
        psi.dcsi=[...
            -1/2*ones(length(csi),1),...
            1/2*ones(length(csi),1)];
        
        psi.deta=[];
        
        psi.d2csi2=zeros(length(csi),3);
        
        nElNds = size(psi.sf,2);
        
    case 8
        % 3 node
        %        1---3---2
        
        ord = 2;
        intRule = ord*intScal(1) + ord*intScal(2);
        [absc, gWts]=integrationRule(3, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        
        psi.sf=[...
            (1/2).*((-1)+csi).*csi,...
            (1/2).*csi.*(1+csi),...
            1+(-1).*csi.^2];
        
        psi.dcsi=[...
            (-1/2)+csi,...
            (1/2)+csi,...
            (-2).*csi];
        
        psi.deta=[];
        
        psi.d2csi2=[...
            ones(length(csi),1),...
            ones(length(csi),1),...
            -2*ones(length(csi),1)];
               
        nElNds = size(psi.sf,2);  
        
    case 2      
        % 3 node
        %       3
        %       | \
        %       |   \
        %       |     \
        %       1------2
            
        [absc, gWts]=integrationRule(1, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            -csi-eta+1,...
            csi,...
            eta];
        
        psi.dcsi=[...
            -ones(length(csi),1),...
            ones(length(csi),1),...
            zeros(length(csi),1)];
        
        psi.deta=[...
            -ones(length(csi),1),...
            zeros(length(csi),1),...
            ones(length(csi),1)];
        
        psi.d2csi2=zeros(length(csi),3);
        
        psi.d2csieta=zeros(length(csi),3);
        
        psi.d2eta2=zeros(length(csi),3);
        
        nElNds = size(psi.sf,2);
        
    case 9
        % 6 node
        %       3
        %       | \
        %       6   5
        %       |     \
        %       1---4---2
        
        [absc, gWts]=integrationRule(1, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            (-1 + eta + csi).*(-1 + 2.*eta + 2.*csi),...
            csi.*(-1 + 2.*csi),...
            eta.*(-1 + 2.*eta),...
            -4.*csi.*(-1 + eta + csi),...
            4.*eta.*csi,...
            -4.*eta.*(-1 + eta + csi)];
        
        psi.dcsi=[...
            -3 + 4.*eta + 4.*csi,...
            -1 + 4.*csi,...
            zeros(length(csi),1),...
            -4.*(-1 + eta + 2.*csi),...
            4.*eta,...
            -4.*eta];
        
        psi.deta=[...
            -3 + 4.*eta + 4.*csi,...
            zeros(length(csi),1),...
            -1 + 4.*eta,...
            -4.*csi,...
            4.*csi,...
            -4.*(-1 + 2.*eta + csi)];
        
        psi.d2csi2=[...
            4.*ones(length(csi),1),...
            4.*ones(length(csi),1),...
            zeros(length(csi),1),...
            -8.*ones(length(csi),1),...
            zeros(length(csi),1),...
            zeros(length(csi),1)];
        
        psi.d2csieta=[...
            4.*ones(length(csi),1),...
            zeros(length(csi),1),...
            zeros(length(csi),1),...
            -4.*ones(length(csi),1),...
            4.*ones(length(csi),1),...
            -4.*ones(length(csi),1)];
        
        psi.d2eta2=[...
            4.*ones(length(csi),1),...
            zeros(length(csi),1),...
            4.*ones(length(csi),1),...
            zeros(length(csi),1),...
            zeros(length(csi),1),...
            -8.*ones(length(csi),1)];
                
        nElNds = size(psi.sf,2);

    case 21
        % 10 node        
        %       3
        %       | \
        %       6   8
        %       |     \
        %       9  10   5
        %       |         \
        %       1--4----7--2
        
        [absc, gWts]=integrationRule(1, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            -((-1 + eta + csi).*(-2 + 3.*eta + 3.*csi).*(-1 + 3.*eta + 3.*csi))/2.,...
            (csi.*(2 + 9.*(-1 + csi).*csi))/2.,...
            (eta.*(2 + 9.*(-1 + eta).*eta))/2.,...
            (9.*csi.*(-1 + eta + csi).*(-2 + 3.*eta + 3.*csi))/2.,...
            (9.*eta.*csi.*(-1 + 3.*csi))/2.,...
            (-9.*eta.*(-1 + 3.*eta).*(-1 + eta + csi))/2.,...
            (-9.*csi.*(-1 + eta + csi).*(-1 + 3.*csi))/2.,...
            (9.*eta.*(-1 + 3.*eta).*csi)/2.,...
            (9.*eta.*(-1 + eta + csi).*(-2 + 3.*eta + 3.*csi))/2.,...
            -27.*eta.*csi.*(-1 + eta + csi)];
        
        psi.dcsi=[...
            (-11 + 36.*csi - 9.*(eta.*(-4 + 3.*eta) + 6.*eta.*csi + 3.*csi.^2))/2.,...
            1 + (9.*csi.*(-2 + 3.*csi))/2.,...
            zeros(length(csi),1),...
            (9.*(2 + 3.*eta.^2 + csi.*(-10 + 9.*csi) + eta.*(-5 + 12.*csi)))/2.,...
            (9.*eta.*(-1 + 6.*csi))/2.,...
            (9.*(1 - 3.*eta).*eta)/2.,...
            (-9.*(1 + eta.*(-1 + 6.*csi) + csi.*(-8 + 9.*csi)))/2.,...
            (9.*eta.*(-1 + 3.*eta))/2.,...
            (9.*eta.*(-5 + 6.*eta + 6.*csi))/2.,...
            -27.*eta.*(-1 + eta + 2.*csi)];
        
        psi.deta=[...
            (-11 + 36.*csi - 9.*(eta.*(-4 + 3.*eta) + 6.*eta.*csi + 3.*csi.^2))/2.,...
            zeros(length(csi),1),...
            1 + (9.*eta.*(-2 + 3.*eta))/2.,...
            (9.*csi.*(-5 + 6.*eta + 6.*csi))/2.,...
            (9.*csi.*(-1 + 3.*csi))/2.,...
            (-9.*(1 - csi + eta.*(-8 + 9.*eta + 6.*csi)))/2.,...
            (9.*(1 - 3.*csi).*csi)/2.,...
            (9.*(-1 + 6.*eta).*csi)/2.,...
            (9.*(2 + 9.*eta.^2 - 5.*csi + 3.*csi.^2 + 2.*eta.*(-5 + 6.*csi)))/2.,...
            -27.*csi.*(-1 + 2.*eta + csi)];
        
        psi.d2csi2=[...
            -9.*(-2 + 3.*eta + 3.*csi),...
            -9 + 27.*csi,...
            zeros(length(csi),1),...
            9.*(-5 + 6.*eta + 9.*csi),...
            27.*eta,...
            zeros(length(csi),1),...
            -9.*(-4 + 3.*eta + 9.*csi),...
            zeros(length(csi),1),...
            27.*eta,...
            -54.*eta];
        
        psi.d2csieta=[...
            -9.*(-2 + 3.*eta + 3.*csi),...
            zeros(length(csi),1),...
            zeros(length(csi),1),...
            (9.*(-5 + 6.*eta + 12.*csi))/2.,...
            -4.5 + 27.*csi,...
            4.5 - 27.*eta,...
            4.5 - 27.*csi,...
            -4.5 + 27.*eta,...
            (9.*(-5 + 12.*eta + 6.*csi))/2.,...
            -27.*(-1 + 2.*eta + 2.*csi)];
        
        psi.d2eta2=[...
            -9.*(-2 + 3.*eta + 3.*csi),...
            zeros(length(csi),1),...
            -9 + 27.*eta,...
            27.*csi,...
            zeros(length(csi),1),...
            -9.*(-4 + 9.*eta + 3.*csi),...
            zeros(length(csi),1),...
            27.*csi,...
            9.*(-5 + 9.*eta + 6.*csi),...
            -54.*csi];
               
        nElNds = size(psi.sf,2);

    case 3
        % 4 node      
        %       4--------3
        %       |        |
        %       |        |
        %       |        |
        %       1--------2
        
        ord = 1;
        intRule = ord*intScal(1) + ord*intScal(2);
        [absc, gWts]=integrationRule(2, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            1/4.*(1-csi).*(1-eta),...
            1/4.*(1+csi).*(1-eta),...
            1/4.*(1+csi).*(1+eta),...
            1/4.*(1-csi).*(1+eta)];

        psi.dcsi=[...
            1/4.*(-1).*(1-eta),...
            1/4.*(1).*(1-eta),...
            1/4.*(1).*(1+eta),...
            1/4.*(-1).*(1+eta)];
        
        psi.deta=[...
            1/4.*(1-csi).*(-1),...
            1/4.*(1+csi).*(-1),...
            1/4.*(1+csi).*(1),...
            1/4.*(1-csi).*(1)];
        
        psi.d2csi2=zeros(length(csi),4);
        
        psi.d2csieta=[...
            1/4.*ones(length(csi),1),...
            -1/4.*ones(length(csi),1),...
            1/4.*ones(length(csi),1),...
            -1/4.*ones(length(csi),1)];
        
        psi.d2eta2=zeros(length(csi),4);
               
        nElNds = size(psi.sf,2);

    case 16
        % 8 node      
        %       4---7----3
        %       |        |
        %       8        6
        %       |        |
        %       1---5----2
        
        ord = 2;
        intRule = ord*intScal(1) + ord*intScal(2);
        [absc, gWts]=integrationRule(2, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            -((-1 + eta).*(-1 + csi).*(1 + eta + csi))/4.,...
            ((-1 + eta).*(1 + eta - csi).*(1 + csi))/4.,...
            ((1 + eta).*(1 + csi).*(-1 + eta + csi))/4.,...
            -((1 + eta).*(-1 + eta - csi).*(-1 + csi))/4.,...
            ((-1 + eta).*(-1 + csi.^2))/2.,...
            -((-1 + eta.^2).*(1 + csi))/2.,...
            -((1 + eta).*(-1 + csi.^2))/2.,...
            ((-1 + eta.^2).*(-1 + csi))/2.];
        
        psi.dcsi=[...
            -((-1 + eta).*(eta + 2.*csi))/4.,...
            ((-1 + eta).*(eta - 2.*csi))/4.,...
            ((1 + eta).*(eta + 2.*csi))/4.,...
            -((1 + eta).*(eta - 2.*csi))/4.,...
            (-1 + eta).*csi,...
            (1 - eta.^2)/2.,...
            -((1 + eta).*csi),...
            (-1 + eta.^2)/2.];
        
        psi.deta=[...
            -((-1 + csi).*(2.*eta + csi))/4.,...
            ((2.*eta - csi).*(1 + csi))/4.,...
            ((1 + csi).*(2.*eta + csi))/4.,...
            -((2.*eta - csi).*(-1 + csi))/4.,...
            (-1 + csi.^2)/2.,...
            -(eta.*(1 + csi)),...
            (1 - csi.^2)/2.,...
            eta.*(-1 + csi)];
        
        psi.d2csi2=[...
            (1 - eta)/2.,...
            (1 - eta)/2.,...
            (1 + eta)/2.,...
            (1 + eta)/2.,...
            (eta - 1),...
            zeros(length(csi),1),...
            (-eta - 1),...
            zeros(length(csi),1)];
        
        psi.d2csieta=[...
            (1 - 2.*eta - 2.*csi)/4.,...
            (-1 + 2.*eta - 2.*csi)/4.,...
            (1 + 2.*eta + 2.*csi)/4.,...
            (-1 - 2.*eta + 2.*csi)/4.,...
            csi,...
            -eta,...
            -csi,...
            eta];
        
        psi.d2eta2=[...
            (1 - csi)/2.,...
            (1 + csi)/2.,...
            (1 + csi)/2.,...
            (1 - csi)/2.,...
            zeros(length(csi),1),...
            (-csi - 1),...
            zeros(length(csi),1),...
            (csi - 1)];
               
        nElNds = size(psi.sf,2);

    case 10
        % 9 node      
        %       4---7----3
        %       |        |
        %       8   9    6
        %       |        |
        %       1---5----2
        
        ord = 2;
        intRule = ord*intScal(1) + ord*intScal(2);
        [absc, gWts]=integrationRule(2, intRule);
        dim = size(absc,1);
        csi = absc(1,:)';
        eta = absc(2,:)';
        
        psi.sf=[...
            ((-1 + eta).*eta.*(-1 + csi).*csi)/4.,...
            ((-1 + eta).*eta.*csi.*(1 + csi))/4.,...
            (eta.*(1 + eta).*csi.*(1 + csi))/4.,...
            (eta.*(1 + eta).*(-1 + csi).*csi)/4.,...
            -((-1 + eta).*eta.*(-1 + csi.^2))/2.,...
            -((-1 + eta.^2).*csi.*(1 + csi))/2.,...
            -(eta.*(1 + eta).*(-1 + csi.^2))/2.,...
            -((-1 + eta.^2).*(-1 + csi).*csi)/2.,...
            (-1 + eta.^2).*(-1 + csi.^2)];
        
        psi.dcsi=[...
            ((-1 + eta).*eta.*(-1 + csi))/4. + ((-1 + eta).*eta.*csi)/4.,...
            ((-1 + eta).*eta.*csi)/4. + ((-1 + eta).*eta.*(1 + csi))/4.,...
            (eta.*(1 + eta).*csi)/4. + (eta.*(1 + eta).*(1 + csi))/4.,...
            (eta.*(1 + eta).*(-1 + csi))/4. + (eta.*(1 + eta).*csi)/4.,...
            -((-1 + eta).*eta.*csi),...
            -((-1 + eta.^2).*csi)/2. - ((-1 + eta.^2).*(1 + csi))/2.,...
            -(eta.*(1 + eta).*csi),...
            -((-1 + eta.^2).*(-1 + csi))/2.-((-1 + eta.^2).*csi)/2.,...
            2.*(-1 + eta.^2).*csi];
        
        psi.deta=[...
            ((-1 + eta).*(-1 + csi).*csi)/4. + (eta.*(-1 + csi).*csi)/4.,...
            ((-1 + eta).*csi.*(1 + csi))/4. + (eta.*csi.*(1 + csi))/4.,...
            (eta.*csi.*(1 + csi))/4. + ((1 + eta).*csi.*(1 + csi))/4.,...
            (eta.*(-1 + csi).*csi)/4. + ((1 + eta).*(-1 + csi).*csi)/4.,...
            -((-1 + eta).*(-1 + csi.^2))/2. - (eta.*(-1 + csi.^2))/2.,...
            -(eta.*csi.*(1 + csi)),...
            -(eta.*(-1 + csi.^2))/2. - ...
            ((1 + eta).*(-1 + csi.^2))/2.,...
            -(eta.*(-1 + csi).*csi),...
            2.*eta.*(-1 + csi.^2)];
        
        psi.d2csi2=[...
            ((-1 + eta).*eta)/2.,...
            ((-1 + eta).*eta)/2.,...
            (eta.*(1 + eta))/2.,...
            (eta.*(1 + eta))/2.,...
            -((-1 + eta).*eta),...
            1 - eta.^2,...
            -(eta.*(1 + eta)),...
            1 - eta.^2,...
            2.*(-1 + eta.^2)];
        
        psi.d2csieta=[...
            ((-1 + 2.*eta).*(-1 + 2.*csi))/4.,...
            ((-1 + 2.*eta).*(1 + 2.*csi))/4.,...
            ((1 + 2.*eta).*(1 + 2.*csi))/4.,...
            ((1 + 2.*eta).*(-1 + 2.*csi))/4.,...
            csi - 2.*eta.*csi,...
            -(eta.*(1 + 2.*csi)),...
            -((1 + 2.*eta).*csi),...
            eta - 2.*eta.*csi,...
            4.*eta.*csi];
        
        psi.d2eta2=[...
            ((-1 + csi).*csi)/2.,...
            (csi.*(1 + csi))/2.,...
            (csi.*(1 + csi))/2.,...
            ((-1 + csi).*csi)/2.,...
            1 - csi.^2,...
            -(csi.*(1 + csi)),...
            1 - csi.^2,...
            -((-1 + csi).*csi),...
            2.*(-1 + csi.^2)];
               
        nElNds = size(psi.sf,2);



    case 15
        % 1-noded point element    
        psi.sf = 1;
        gWts = 1;
        gPts = 1;
        nElNds = 1;
        dim = 0;
end

end
%
% csi = -1:.1:1;
% eta = -1:.1:1;
% [csi,eta] = meshgrid(csi,eta);
% 
% zz=1/4.*(1-csi).*(1-eta);
% surfl(csi,eta,zz);
% xlabel('\xi');ylabel('\eta')

